In [2]:
#Importing library 'numpy' as alias np
import numpy as np 

In [4]:
#Using arrays from numpy
a= np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
#Implementing n-D arrays
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#print an array of 0's
a=np.zeros(2)
print(a)

[0. 0.]


In [7]:
#print an array of 1's
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [14]:
#Empty: returns an array of given shape/type with random values
aa=np.empty(4)
print(aa)

[1. 1. 1. 1.]


In [18]:
#Print values within range 7
a=np.arange(7)
print(a)
#print values in range 1-6 with a difference of 2
b=np.arange(1,6,2)
print(b)

[0 1 2 3 4 5 6]
[1 3 5]


In [19]:
#delete an element from array using index
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)
a=np.delete(a, 1)
print(a)

[1 2 3 4 5 6 7 8]
[1 3 4 5 6 7 8]


In [27]:
a = np.array([8,2,5,1,6,7])
print(a)
#Sort the array using function 'sort()'
a=np.sort(a)
print(a)
#find shape of array using function 'shape()'
b=np.shape(a)
print(b)

[8 2 5 1 6 7]
[1 2 5 6 7 8]
(6,)


In [35]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
#reshape the array with different no. of rows and columns with same elements
b = a.reshape(4,2)
print(b)
#ndim:find the number of dimensions of array
c=a.ndim
print(c)
#find the size of array(no. of elements)
d=a.size
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2
8


In [40]:
#Find the number of dimensions of array
a=np.array(2)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c=a.ndim
d=b.ndim
print(c)
print(d)

0
3


In [41]:
#Perform airthmatic operations using functions
a=np.array(9)
print(a)
b=np.array([10,20,30])
print(b)
addition= np.add(a,b)
print("Addition", addition)
sub=np.subtract(b,a)
print("Subtraction =",sub)
mul=np.multiply (a,b)
print("Multiplcation =",mul)
div=np.divide (b,a)
print("Division =",div)
div1=np.divide (b,5)
print("Division =",div1)

9
[10 20 30]
Addition [19 29 39]
Subtraction = [ 1 11 21]
Multiplcation = [ 90 180 270]
Division = [1.11111111 2.22222222 3.33333333]
Division = [2. 4. 6.]


In [42]:
#find reciprocal of the elements of array
a= np.array([0.5,1.8,2.441,3.14])
print(a)
rec=np.reciprocal(a) 
print(rec)

[0.5   1.8   2.441 3.14 ]
[2.         0.55555556 0.40966817 0.31847134]


In [43]:
#find mod and remainder
a= np.array ([10,20,30])
b= np.array ([3,5,7])
print(a)
print(b)
mm=np.mod(a,b)
rm=np.remainder(a,b)
print("MOD=", mm)
print("REMAINDER=", rm)

[10 20 30]
[3 5 7]
MOD= [1 0 2]
REMAINDER= [1 0 2]


In [44]:
#find the real, imaginary and conjugate part of the elements
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)
print("real=",np.real(a))
print("imaginary=",np.imag(a))
print("Conjugate=", np.conj(a))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [45]:
a=np.array ([1.0,5.3,123,0.56,25.5,32])
print(a)
#round the number
print(np.around(a))
#round the number with 1 decimal digit precision
print(np.around(a,decimals=1))

[  1.     5.3  123.     0.56  25.5   32.  ]
[  1.   5. 123.   1.  26.  32.]
[  1.    5.3 123.    0.6  25.5  32. ]


In [46]:
#Use the floor and ceil function
a=np.array ([1.0,-5.3,123,-0.56,25.5,32])
print(a)
print("Floor",np.floor(a))
print("Ceil",np.ceil(a))

[  1.    -5.3  123.    -0.56  25.5   32.  ]
Floor [  1.  -6. 123.  -1.  25.  32.]
Ceil [  1.  -5. 123.  -0.  26.  32.]


In [48]:
#find power using base and exponent 
a=np.array([10,100,1000])
pow=np.power(a,2)
print(pow)
b=np.array([5,3,2])
p=np.power(a,b)
print(p)

[    100   10000 1000000]
[ 100000 1000000 1000000]


In [3]:
#Search the postions of the elements of array
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [6]:
#Search sorted is used search number of elements less than given number(to the left by default) 
arr = np.array([6, 7, 18, 19])
x = np.searchsorted(arr,11)
print(x)

2


In [7]:
#Search to the right side of the given number
arr = np.array([6, 7, 18, 29])
x = np.searchsorted(arr, 19, side='right')
print(x)

3


In [13]:
#Slicing in python means taking elements from one given index to another given index.[start:end] [start:end:step].
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) 
print(arr[4:])
print(arr[:4])
print(arr[:-1])
print(arr[::2]) 

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[1 2 3 4 5 6]
[1 3 5 7]


In [19]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])
print(arr[2,0:2])
print(arr[1,1:3])
print(arr[0:2, 1:4])

[11 12]
[7 8]
[[2 3 4]
 [7 8 9]]


In [20]:
#Concatination: Adding an existing array to another
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr) 

[1 2 3 4 5 6]


In [21]:
arr1 = np.array([[1, 2], [3, 4]])
print(arr1) 
arr2 = np.array([[5, 6], [7, 8]])
print(arr2) 
print("Conactination")
arr = np.concatenate((arr1, arr2), axis=1) #0=row, 1=col
print(arr) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Conactination
[[1 2 5 6]
 [3 4 7 8]]


In [22]:
arr1 = np.array([[1, 2], [3, 4]])
print(arr1) 
arr2 = np.array([[5, 6], [7, 8]])
print(arr2) 
print("Conactination")
arr = np.concatenate((arr1, arr2), axis=0) #1=row, 0=col
print(arr) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Conactination
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
#hstack:combine arrays into 1 single horizontal array
#vstack"combine arrays into 1 single vertical array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
a = np.hstack((arr1, arr2))
ar = np.vstack((arr1, arr2))
print("hstack",a) 
print("vstack",ar)

hstack [1 2 3 4 5 6]
vstack [[1 2 3]
 [4 5 6]]


In [24]:
a = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])
b = np.array([[7,8,9],[77,88,99],[777,888,999],[7777,8888,9999]])
print("\nhstack =\n", np.hstack((a,b)))
print("\n")
print("\nvstack =\n", np.vstack((a,b)))
arr = np.concatenate((a, b), axis=0)
print("\n")
print("\n concatenate at axis 0=\n",arr)
arr1 = np.concatenate((a, b), axis=1)
print("\n")
print("\n concatenate at axis 1=\n",arr1)


hstack =
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]



vstack =
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]



 concatenate at axis 0=
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]



 concatenate at axis 1=
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]


In [26]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
print(np.stack([a,b]))
np.stack([a,b]).reshape(-1)

[[1 2 3]
 [5 6 7]]


array([1, 2, 3, 5, 6, 7])

In [27]:
a = np.array((1,2,3))
b = np.array((7,8,9))
print(a)
print(b)

print("vstack\n")
print(np.vstack((a,b)))
print("concatenate\n")
print(np.concatenate([a.reshape(1,3),b.reshape(1,3)]))
print("stack\n")
print(np.stack((a,b),axis=1))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 1))
print("stack\n")
print(np.stack((a,b),axis=0))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 0))

[1 2 3]
[7 8 9]
vstack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
stack

[[1 7]
 [2 8]
 [3 9]]
concatenate

[[1 2 3 7 8 9]]
stack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]


In [30]:
#split:splits the elements of array into separate arrays
arr = np.array([1, 2, 3, 4, 5, 6])
a=np.array_split(arr,5)
print(a)
newarr = np.array_split(arr, 3)#splits into 3 arrays
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
#splitting and printing each array separately
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print("Array 1:")
print(newarr[0])
print("Array 2:")
print(newarr[1])
print("Array 3:")
print(newarr[2])

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Array 3:
[[ 9 10]
 [11 12]]


In [36]:
#hsplit:splits array horizontally
#vsplit:splits array vertically
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
a = np.vsplit(arr, 3)
print("hsplit\n",newarr)
print("vsplit\n",a)

hsplit
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
vsplit
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [39]:
#split using axis as 1 and 0
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
na = np.array_split(arr, 3, axis=0)
print("Split with axis=1\n",newarr)
print("Split with axix=0\n",na)

Split with axis=1
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
Split with axix=0
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
